<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClubsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clubs = [
            [
                'currency_id' => 1,
                'name' => 'Banfield de Ramos Mejia',
                'logo' => 'clubs/logos/1751402903_68644997b3c59.jpg',
                'cuit' => NULL,
                'responsible' => 'Edgardo Morel',
                'phone' => '+5491155064038',
                'email' => 'edgardomorel@hotmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 2,
            ],
            [
                'id' => 3,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Los Picapiedras',
                'logo' => 'clubs/logos/1751417746_6864839223aa3.jpg',
                'cuit' => NULL,
                'responsible' => 'Lucas',
                'phone' => '+5491150536261',
                'email' => 'lucasalejandro215@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 2,
               
            ],
            [
                'id' => 4,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Las Banderas FC',
                'logo' => 'clubs/logos/1751417714_68648372a7264.jpeg',
                'cuit' => NULL,
                'responsible' => 'Hernan Maximiliano Henriquez',
                'phone' => '+5491130358759',
                'email' => 'maxihernanenriquez86@live.com.ar',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 2,
               
            ],
            [
                'id' => 5,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Academia Kaly',
                'logo' => 'clubs/logos/1751392931_686422a301c75.jpg',
                'cuit' => NULL,
                'responsible' => 'Fernando Granados',
                'phone' => '+5491155064655',
                'email' => 'granados.fernando@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 10,
            ],
            [
                'id' => 6,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Def de Plaza España 2015',
                'logo' => 'clubs/logos/1751403087_68644a4f24bd7.jpg',
                'cuit' => NULL,
                'responsible' => 'German Rodriguez',
                'phone' => '+5492345415794',
                'email' => 'rodriguezgerman319@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 11,
                'has_accommodation' => 0,
                'players_quantity' => 12,
                'player_price' => 160000.00,
                'total_players' => 1920000.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 12,
                'total_amount' => 1920000.00,
                'created_at' => '2025-06-28 20:21:58',
                'updated_at' => '2025-07-01 18:51:27'
            ],
            [
                'id' => 7,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => 3,
                'name' => 'Def de Plaza España 2011',
                'logo' => 'clubs/logos/1751403074_68644a42a613a.jpg',
                'cuit' => NULL,
                'responsible' => 'German Rodriguez',
                'phone' => '+5492345415794',
                'email' => 'rodriguezgerman319@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 11,
                'has_accommodation' => 1,
                'players_quantity' => 16,
                'player_price' => 390000.00,
                'total_players' => 6240000.00,
                'teachers_quantity' => 4,
                'teacher_price' => 390000.00,
                'total_teachers' => 1560000.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 20,
                'total_amount' => 7800000.00,
                'created_at' => '2025-06-28 20:29:00',
                'updated_at' => '2025-07-01 18:51:14'
            ],
            [
                'id' => 8,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Dina Huapi',
                'logo' => 'clubs/logos/1751403049_68644a296a14f.png',
                'cuit' => NULL,
                'responsible' => 'Guillermo Pasteris',
                'phone' => '+5492944800412',
                'email' => 'ppasteris1@hotmail.com',
                'country_id' => 1,
                'province_id' => 2,
                'city_id' => 4,
                'has_accommodation' => 1,
                'players_quantity' => 15,
                'player_price' => 470000.00,
                'total_players' => 7050000.00,
                'teachers_quantity' => 3,
                'teacher_price' => 470000.00,
                'total_teachers' => 1410000.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 18,
                'total_amount' => 8460000.00,
                'created_at' => '2025-06-28 20:35:05',
                'updated_at' => '2025-07-01 18:50:49'
            ],
            [
                'id' => 9,
                'event_id' => 1,
                'category_income_id' => 1,
                'currency_id' => 2,
                'supplier_id' => 4,
                'name' => 'La Cantera F. C.',
                'logo' => 'clubs/logos/1751417674_6864834a2ada6.jpeg',
                'cuit' => NULL,
                'responsible' => 'Maria Karolina Cano',
                'phone' => '+5493764747461',
                'email' => 'karolinacano20@hotmail.com',
                'country_id' => 1,
                'province_id' => 7,
                'city_id' => 12,
                'has_accommodation' => 1,
                'players_quantity' => 30,
                'player_price' => 360.00,
                'total_players' => 10800.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 12,
                'companion_price' => 360.00,
                'total_companions' => 4320.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 42,
                'total_amount' => 15120.00,
                'created_at' => '2025-06-28 20:47:12',
                'updated_at' => '2025-07-01 22:54:34'
            ],
            [
                'id' => 10,
                'event_id' => 1,
                'category_income_id' => 1,
                'currency_id' => 2,
                'supplier_id' => NULL,
                'name' => 'Bartolome Mitre',
                'logo' => 'clubs/logos/1751402864_68644970e1edf.png',
                'cuit' => NULL,
                'responsible' => 'Ana Maria Malvido',
                'phone' => '+5493764901573',
                'email' => 'Yoganita2022@gmail.com',
                'country_id' => 1,
                'province_id' => 7,
                'city_id' => 12,
                'has_accommodation' => 1,
                'players_quantity' => 23,
                'player_price' => 360.00,
                'total_players' => 8280.00,
                'teachers_quantity' => 3,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 30,
                'companion_price' => 360.00,
                'total_companions' => 10800.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 3,
                'total_people' => 59,
                'total_amount' => 19080.00,
                'created_at' => '2025-06-28 21:03:12',
                'updated_at' => '2025-07-01 18:47:44'
            ],
            [
                'id' => 11,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Newells Old Boys de El Calafate',
                'logo' => 'clubs/logos/1751417770_686483aadb563.jpg',
                'cuit' => '30714180378',
                'responsible' => 'Gustavo Hernan Ruiz',
                'phone' => '+5492966465170',
                'email' => 'ghr9405@gmail.com',
                'country_id' => 1,
                'province_id' => 3,
                'city_id' => 3,
                'has_accommodation' => 1,
                'players_quantity' => 32,
                'player_price' => 430000.00,
                'total_players' => 13760000.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 32,
                'total_amount' => 13760000.00,
                'created_at' => '2025-06-28 21:29:28',
                'updated_at' => '2025-07-01 22:56:10'
            ],
            [
                'id' => 12,
                'event_id' => 2,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Pacifico Neuquen',
                'logo' => 'clubs/logos/1751155957_686084f52eab0.png',
                'cuit' => NULL,
                'responsible' => 'Mario Facundo Villagra',
                'phone' => '+5492942550476',
                'email' => 'Facu.v309@gmail.com',
                'country_id' => 1,
                'province_id' => 11,
                'city_id' => 14,
                'has_accommodation' => 1,
                'players_quantity' => 55,
                'player_price' => 45000.00,
                'total_players' => 2475000.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 55,
                'total_amount' => 2475000.00,
                'created_at' => '2025-06-28 21:40:09',
                'updated_at' => '2025-06-28 22:12:37'
            ],
            [
                'id' => 13,
                'event_id' => 3,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Roma CF',
                'logo' => 'clubs/logos/1751159430_68609286102de.png',
                'cuit' => NULL,
                'responsible' => 'Rodrigo Mases',
                'phone' => '+5491130468502',
                'email' => 'Rodrigo@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 1,
                'has_accommodation' => 0,
                'players_quantity' => 82,
                'player_price' => 60000.00,
                'total_players' => 4920000.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 82,
                'total_amount' => 4920000.00,
                'created_at' => '2025-06-28 23:10:30',
                'updated_at' => '2025-07-07 21:32:18'
            ],
            [
                'id' => 14,
                'event_id' => 3,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'CEFI',
                'logo' => 'clubs/logos/1751162369_68609e0197fbc.png',
                'cuit' => NULL,
                'responsible' => 'Diego Laterza',
                'phone' => '+5491155684243',
                'email' => 'diego@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 17,
                'has_accommodation' => 0,
                'players_quantity' => 10,
                'player_price' => 60000.00,
                'total_players' => 600000.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 10,
                'total_amount' => 600000.00,
                'created_at' => '2025-06-28 23:59:29',
                'updated_at' => '2025-06-28 23:59:29'
            ],
            [
                'id' => 15,
                'event_id' => 3,
                'category_income_id' => 1,
                'currency_id' => 1,
                'supplier_id' => NULL,
                'name' => 'Academia F. C.',
                'logo' => 'clubs/logos/1751162618_68609efada75f.jpg',
                'cuit' => NULL,
                'responsible' => 'Pablo',
                'phone' => '+5491128475199',
                'email' => 'pablo@gmail.com',
                'country_id' => 1,
                'province_id' => 1,
                'city_id' => 17,
                'has_accommodation' => 0,
                'players_quantity' => 53,
                'player_price' => 50000.00,
                'total_players' => 2650000.00,
                'teachers_quantity' => 0,
                'teacher_price' => 0.00,
                'total_teachers' => 0.00,
                'companions_quantity' => 0,
                'companion_price' => 0.00,
                'total_companions' => 0.00,
                'drivers_quantity' => 0,
                'driver_price' => 0.00,
                'total_drivers' => 0.00,
                'liberated_quantity' => 0,
                'total_people' => 53,
                'total_amount' => 2650000.00,
                'created_at' => '2025-06-29 00:03:38',
                'updated_at' => '2025-07-12 13:54:25'
            ]
        ];

        // Insertar los clubs
        foreach ($clubs as $club) {
            DB::table('clubs')->insert($club);
        }

        $this->command->info('Se han insertado los clubs de ejemplo.');
    }
}
